### ISSUE TITLE
Can't do /cobblegen admin and sometime neither /cobblegen

### ISSUE THREAD

**Issue by RayUniverse** [phil14052/CustomCobbleGen#44]
Version on my server is 1.12.2 with viaversion

When i digite /cobblegen admin and sometime with /cobblegen does this error

[12:12:32] [Server thread/INFO]: RayMitsujy issued server command: /cobblegen admin
[12:12:32] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cobblegen' in plugin CustomCobbleGen v1.4.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
	at com.wasteofplastic.askyblock.PlayerCache.getIslandLocation(PlayerCache.java:314) ~[?:?]
	at com.wasteofplastic.askyblock.ASkyBlockAPI.getIslandLocation(ASkyBlockAPI.java:154) ~[?:?]
	at me.phil14052.CustomCobbleGen.Hooks.ASkyBlockHook.getIslandFromPlayer(ASkyBlockHook.java:35) ~[?:?]
	at me.phil14052.CustomCobbleGen.Hooks.ASkyBlockHook.getIslandLeaderFromPlayer(ASkyBlockHook.java:49) ~[?:?]
	at me.phil14052.CustomCobbleGen.Managers.TierManager.getSelectedTiers(TierManager.java:210) ~[?:?]
	at me.phil14052.CustomCobbleGen.Files.Lang.replacePlaceholders(Lang.java:241) ~[?:?]
	at me.phil14052.CustomCobbleGen.Files.Lang.toString(Lang.java:279) ~[?:?]
	at me.phil14052.CustomCobbleGen.GUI.GUIManager$AdminGUI.<init>(GUIManager.java:457) ~[?:?]
	at me.phil14052.CustomCobbleGen.Commands.MainCommand.onCommand(MainCommand.java:185) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
	... 15 more

**Comment by phil14052** [comment]
Can you send me your config?

**Comment by RayUniverse** [comment]
I resolved, thanks

Il ven 5 feb 2021, 11:01 phil14052 <notifications@github.com> ha scritto:
