### ISSUE TITLE
Error occurred while enabling CustomCobbleGen

### ISSUE THREAD

**Issue by Plexi09** [phil14052/CustomCobbleGen#58]
**Describe the bug**
When i start my server, i get an error and the plugin does not works

**To Reproduce**
Install the plugin
Start the server

**Expected behavior**

**Console errors**
```
[15:36:00 ERROR]: Error occurred while enabling CustomCobbleGen v1.5.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.phil14052.CustomCobbleGen.Managers.GeneratorModeManager.loadFromConfig(GeneratorModeManager.java:121) ~[CustomCobbleGen-Base-1.5.0.jar:?]
	at me.phil14052.CustomCobbleGen.CustomCobbleGen.onEnable(CustomCobbleGen.java:82) ~[CustomCobbleGen-Base-1.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-478]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-478]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-478]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-478]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-478]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-478]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-478]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-478]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-478]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at xyz.xenondevs.particle.ParticleEffect.<clinit>(ParticleEffect.java:1304) ~[CustomCobbleGen-Base-1.5.0.jar:?]
	... 14 more
[15:36:00 INFO]: [CustomCobbleGen] Disabling CustomCobbleGen v1.5.0
[15:36:00 INFO]:  [  CustomCobbleGen  ]:   Log   -  Disabling CustomCobbleGen  ✓ 
[15:36:00 INFO]:  [  CustomCobbleGen  ]:   Log   -  CustomCobbleGen is now disabled  ✓ 
```

**Config file**
There is none

**Screenshots**
![image](https://github.com/PhilipFlyvholm/CustomCobbleGen/assets/138695340/69d17560-db1f-49c9-8fcd-e205eac95d65)

**System (please complete the following information):**
 - OS: Linux
 - Plugin version: 1.5.0
 - MC version: 1.20.4
**Additional context**
I'm using paper

**Comment by Xitryne** [comment]
Le plugin n'est plus à jour, je pense recruter quelqu'un sur Fiverr pour le maintenir
